// export const REQUEST_ITEMS = 'REQUEST_ITEMS';
// export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';
// export const REQUEST_ITEMS_FAILURE = 'REQUEST_ITEMS_FAILURE';
// export const PROCEED_TO_FAVORITES = 'PROCEED_TO_FAVORITES';
// export const EXIT_FAVORITES = 'EXIT_FAVORITES';

// //new actionType for onChange
// export const FORM_ONCHANGE = 'FORM_ONCHANGE';
// export const CREATE_ACCOUNT_STORE = 'CREATE_ACCOUNT_STORE';
const actionTypes = {
  REQUEST_ITEMS: 'REQUEST_ITEMS',
  RECEIVE_ITEMS: 'RECEIVE_ITEMS',
  REQUEST_ITEMS_FAILURE: 'REQUEST_ITEMS_FAILURE',
  PROCEED_TO_FAVORITES: 'PROCEED_TO_FAVORITES',
  EXIT_FAVORITES: 'EXIT_FAVORITES',
  ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
  FORM_ONCHANGE: 'FORM_ONCHANGE',
  CREATE_ACCOUNT_STORE: 'CREATE_ACCOUNT_STORE'
};

export default actionTypes;
