const actionTypes = {
  REQUEST_ITEMS: "REQUEST_ITEMS",
  RECEIVE_ITEMS: "RECEIVE_ITEMS",
  REQUEST_ITEMS_FAILURE: "REQUEST_ITEMS_FAILURE",
  PROCEED_TO_FAVORITES: "PROCEED_TO_FAVORITES",
  EXIT_FAVORITES: "EXIT_FAVORITES",
  ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
  FORM_ONCHANGE: "FORM_ONCHANGE",
  CREATE_ACCOUNT_STORE: "CREATE_ACCOUNT_STORE",
  SEARCH_BY: "SEARCH_BY",
  SEARCH_BYCLICK: "SEARCH_BYCLICK",
  UPDATE_ITEMS: "UPDATE_ITEMS",
  LOGIN: "LOGIN"
};

export default actionTypes;
